<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Done!</title>
    <link rel="stylesheet" href="/css/candidates.css">
</head>

<body>
    <div class="container flex flex-col align-center">
      <h1>${post.name} Success download!</h1>
      <main class="flex flex-wrap align-center">
        <div class="card flex flex-col align-center">
          <img src="/images/${post.photo}">

        </div>
      </main>
      <p>-------------------------------------------------------</p>
      <a class="back flex align-center" href="/">back to main </a>

    </div>
</body>

</html>